version: "3"
services:
  product:
    image: pagonxt/product
    build: product

  account:
     image: pagonxt/account
     build: account

  repositories:
      image: pagonxt/repositories
      build: repositories